### ISSUE TITLE
Configure minimum check frequency

### ISSUE THREAD

**Issue by rubencaro** [malko/atom-up2date#2]
Atom is a very active project, and there can be several new releases over a week. `up2date` is sometimes annoying because it will notify you of everyone of these releases. 

It would be great if you could configure the minimum frequency for the notification. This way one could, for example, configure that freq to be a week, and `up2date`, before anything else, would check if there has been at least a week since the last notification.

Hope it's an easy one to implement.

Thanks!

**Comment by malko** [comment]
Hi, sorry for the late response.
It seems like a good idea to me. Will have a look into this asap.

**Comment by malko** [comment]
Will be part of the next release in a few minutes.
Sorry for the time passed since your request but was really busy lately
