### ISSUE TITLE
Avoid beta versions

### ISSUE THREAD

**Issue by rubencaro** [malko/atom-up2date#3]
Since 1.1 there are beta versions in the release process of atom. `up2date` mistakes the last beta for the last version. For instance, I have been notified for days that I had a new version _1.1.0beta_ available, when all I expected was to be notified that there was a _1.0.19_ available. Now I have the actual _1.1.0_ release and now I'm notified that I can download the _1.2.0beta_. I will miss any 1.1.x release.

I would expect beta versions to be avoided. Maybe available optionally.

Thanks.

**Comment by malko** [comment]
Beta version will not be checked by default on next release but an option will be available to keep it if you want so. I'll publish in a few minutes, thanks for your report

**Comment by rubencaro** [comment]
Nice!  Thanks!
