### ISSUE TITLE
Buttons are off the screen

### ISSUE THREAD

**Issue by n-a-m-e** [malko/atom-up2date#4]
If the changelog is too long then i can't close the popup.
maybe add a scrollbar or something to fix.
Anyway thanks for the great package, keep up the good work.
![screenshot_2016-01-14_11-39-44](https://cloud.githubusercontent.com/assets/10303400/12312465/d0d62e70-bab3-11e5-9f56-b10c4eb783fe.png)

**Comment by malko** [comment]
Thanks reporting, should be solved now.

**Comment by n-a-m-e** [comment]
All fixed :+1:
